language: python
python:
  - "2.7"
  - "3.6"
env:
  - DJANGO_VERSION=1.11.10
  - DJANGO_VERSION=2.0.2
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION=2.0.2
install:
  - pip install -U pip
  - pip install -Ur dev_requirements.txt
  - pip install -U .
  - pip install -q Django==$DJANGO_VERSION
before_script:
  - flake8 --exclude=migrations paiji2_forum
script:
  - coverage run --source=paiji2_forum manage.py test
after_success:
  - coverage report
  - coveralls
