language: python
python:
  - "2.7"
env:
  - DJANGO=1.8
  - DJANGO=1.8.4
install:
  - pip install pip -U
  - pip install -q Django==$DJANGO
  - pip install pep8 -U
  - pip install pyflakes -U
  - pip install coveralls -U
  - pip install -r requirements.txt
  - pip install -e .
before_script:
  - pep8 --exclude=migrations paiji2_forum
  - ((pyflakes paiji2_forum) || (exit 0;))
script:
  - coverage run --source=paiji2_forum manage.py test
  - python setup.py test
after_success:
  - coveralls
after_failure:
  - cat validation_errors/*
